--sentence
CREATE TABLE IF NOT EXISTS POLICIES
(
 _ID Int NOT NULL,
 NUMBER Text NOT NULL,
 NAME Text NOT NULL,
 PAYMENT_DAY INT,
 COMMENT Text,
 REMEMBER INT,
 START_REMEMBER_DAY INT,
 END_REMEMBER_DAY INT,
 PAYMENT_INSTRUMENTS_ID INT,
 IMAGE_URI Text,
 BANK_ID INT,
 REMEMBER_PAYMENT INT,
 PLATES Text,
 PRIMARY KEY (_ID),
 UNIQUE(NAME),
 UNIQUE(NUMBER)
)

--sentence
CREATE TABLE IF NOT EXISTS CITIES
(
 _ID Int NOT NULL,
 NAME Text NOT NULL,
 PRIMARY KEY (_ID),
 UNIQUE(NAME)
)

--sentence
CREATE TABLE IF NOT EXISTS BANKS
(
 _ID Int NOT NULL,
 NAME Text NOT NULL,
 PRIMARY KEY (_ID),
 UNIQUE(NAME)
)

--sentence
CREATE TABLE IF NOT EXISTS CONFIG
(
 _ID Int NOT NULL,
 NAME Text NOT NULL,
 VALUE Text NOT NULL,
 PRIMARY KEY (_ID),
 UNIQUE(NAME)
)

--sentence
CREATE TABLE IF NOT EXISTS ALERTS
(
 _ID Int NOT NULL,
 POLICY_ID Int NOT NULL,
 EVENT_ID Int NOT NULL,
 TYPE_ID Int NOT NULL,
 PRIMARY KEY (_ID)
)

--sentence
CREATE TABLE IF NOT EXISTS PAYMENT_INSTRUMENTS
(
 _ID Int NOT NULL,
 NAME Text NOT NULL,
 PRIMARY KEY (_ID),
 UNIQUE(NAME)
)

--sentence
CREATE TABLE IF NOT EXISTS NOTIFICATIONS
(
 _ID Int NOT NULL,
 NAME Text NOT NULL,
 MONTH Int NOT NULL,
 DAY Int NOT NULL,
 TYPE Int NOT NULL,
 POLICY_ID Int NOT NULL,
 PRIMARY KEY (_ID)
)


--sentence
INSERT OR REPLACE INTO CITIES VALUES(1, "Aguascalientes")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(2, "Baja California")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(3, "Baja California Sur")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(4, "Campeche")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(5, "Chiapas")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(6, "Chihuahua")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(7, "Coahuila")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(8, "Colima")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(9, "Distrito Federal")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(10, "Durango")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(11, "Estado de México")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(12, "Guanajuato")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(13, "Guerrero")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(14, "Hidalgo")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(15, "Jalisco")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(16, "Michoacán")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(17, "Morelos")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(18, "Nayarit")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(19, "Nuevo León")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(20, "Oaxaca")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(21, "Puebla")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(22, "Querétaro")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(23, "Quintana Roo")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(24, "San Luis Potosí")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(25, "Sinaloa")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(26, "Sonora")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(27, "Tabasco")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(28, "Tamaulipas")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(29, "Tlaxcala")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(30, "Veracruz")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(31, "Yucatán")
--sentence
INSERT OR REPLACE INTO CITIES VALUES(32, "Zacatecas")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(1, "BANCO NACIONAL DE MEXICO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(2, "BANCO SANTANDER")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(3, "HSBC MEXICO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(4, "SCOTIABANK INVERLAT")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(5, "BBVA BANCOMER")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(6, "BANCO MERCANTIL DEL NORTE")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(7, "BANCO INTERACCIONES")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(8, "BANCO INBURSA")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(9, "BANCA MIFEL")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(10, "BANCO REGIONAL DE MONTERREY")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(11, "BANCO INVEX")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(12, "BANCO DEL BAJIO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(13, "BANSI")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(14, "BANCA AFIRME")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(15, "BANK OF AMERICA MEXICO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(16, "BANCO J.P. MORGAN")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(17, "BANCO VE POR MAS")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(18, "AMERICAN EXPRESS BANK ")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(19, "INVESTA BANK")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(20, "CIBANCO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(21, "BANK OF TOKYO-MITSUBISHI UFJ")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(22, "BANCO MONEX")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(23, "DEUTSCHE BANK MEXICO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(24, "BANCO AZTECA")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(25, "BANCO CREDIT SUISSE")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(26, "BANCO AUTOFIN MEXICO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(27, "BARCLAYS BANK MEXICO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(28, "BANCO AHORRO FAMSA")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(29, "INTERCAM BANCO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(30, "ABC CAPITAL")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(31, "BANCO ACTINVER")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(32, "BANCO COMPARTAMOS")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(33, "BANCO MULTIVA")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(34, "UBS BANK MEXICO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(35, "BANCOPPEL")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(36, "CONSUBANCO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(37, "BANCO WAL-MART")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(38, "VOLKSWAGEN BANK")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(39, "BANCO BASE")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(40, "BANCO PAGATODO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(41, "BANCO FORJADORES")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(42, "BANKAOOL")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(43, "BANCO INMOBILIARIO MEXICANO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(44, "DONDE BANCO")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(45, "BANCO BANCREA")
--sentence
INSERT OR REPLACE INTO BANKS VALUES(99, "OTRO")
--sentence
INSERT OR REPLACE INTO PAYMENT_INSTRUMENTS VALUES(1, "TARJETA DE CREDITO")
--sentence
INSERT OR REPLACE INTO PAYMENT_INSTRUMENTS VALUES(2, "TARJETA DE DEBITO")
--sentence
INSERT OR REPLACE INTO PAYMENT_INSTRUMENTS VALUES(3, "TARJETA DE EFECTIVO")
--sentence
INSERT OR REPLACE INTO CONFIG VALUES(1, "REMEMBER_VERIFICATION", "0")




